### PR TITLE
Corrects the IsoCode for a 20ft Open Side

### PR DESCRIPTION
**Pull request by vanherpen**

### CODE REVIEW

**Review by rjayasinghe — APPROVED** [review]
looks good.

**Comment by olle** [comment]
@vanherpen Do you have an available and official source for the ISO-codes - or is it _just_ googleable?

**Comment by contargo-development** [comment]
Are official sources not googleable? ;)

**Comment by olle** [comment]
Touché! 😆 I guess what I ment was if there's some official reference _for us_ that we maybe can link, or refer to, in the code?

**Pull request merged**
